### ISSUE TITLE
org.swt.* feature?

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1250]
@kasemir, is there a feature for org.csstudio.swt.* in appunorganized?
Jenkins is failing because of this.

**Comment by berryma4** [comment]
More specific, the databrowser module is failing because it can't find org.csstudio.swt.rtplot

**Comment by kasemir** [comment]
I wonder how that used to work. As recent as July 13 it built OK for me.
The org.csstudio.trends.databrowser2.feature includes the org.csstudio.swt.rtplot.

**Comment by kasemir** [comment]
Ah, it might be OK when using 'mvn verify' in applications, because it finds the org.csstudio.swt.rtplot sources and compiles them because of org.csstudio.trends.databrowser2.feature.

When you compile module by module, it doesn't work:
applications/appunorganized ignores org.csstudio.swt.rtplot because its in no appunorganized-feature,
applications/databrowser then misses it.

So yes, needs some appunorganized-feature like o.c.swt.rtplot.feature.

**Comment by kasemir** [comment]
Are you creating one, or should I do that?

**Comment by berryma4** [comment]
I will submit a pull request tomorrow.
Thank you!
