### ISSUE TITLE
Alarm Table OPI Widget

### ISSUE THREAD

**Issue by css-iter** [ControlSystemStudio/cs-studio#1252]
Create an Alarm Table OPI widget so that it is possible to include it in any OPI file.

**Comment by mscheng** [comment]
Yes, I agree with you. I also hope to create different OPI alarm widgets so that the alarm system can be designed more flexibly.
----- Original Message ----- 
From: css-iter 
To: ControlSystemStudio/cs-studio 
Date: 2015-07-17, 15:22:29
Subject: [cs-studio] Alarm Table OPI Widget (#1252)


Create an Alarm Table OPI widget so that it is possible to include it in any OPI file.
―

**Comment by berryma4** [comment]
very cool!
