### ISSUE TITLE
Update org.csstudio.opibuilder to 4.1.0

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1254]
Should we update `org.csstudio.opibuilder` to 4.1.0?  There have been significant changes including an interface change.

Or even 5.0.0?

**Comment by kasemir** [comment]
Should certainly increment.

"4.2" would make sense because it'll then match the CSS milestone. The *.opi files are still compatible, so an increment to "5.x" is not necessary for that. But you're right that the behavior of the interface can be quite different when you're _not_ starting out in the OPIRuntime perspective, because the first screen you open will no longer appear in the 'editors' stack.

So call it "5"?

Then, since the operator interface is the most visible part of CSS, do we also call it CSS 5.0? Or do we keep 4.x there because it's based on Eclipse 4.x?

**Comment by willrogers** [comment]
I think it probably is a major change to opibuilder.  Whether it warrants moving all of CS-Studio to 5.0 I don't know.

Your call, I think.

**Comment by berryma4** [comment]
did we do this?  We should.
I would go with 4.2.
I would save 5.0 for Kay's new version.

**Comment by willrogers** [comment]
Happy with whatever the consensus is.
