### ISSUE TITLE
Data Browser prints stack trace when a hidden item is deleted

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1522]
* Open data browser plot
* Deselect 'Show' in the properties panel
* Right-click item in the properties panel and select 'Delete Item'

It looks like it's caught somewhere, but I don't think this should throw an exception.

**Comment by kasemir** [comment]
I can reproduce the error.

When you de-select 'Show', there's a MessageDialog that tells you why hiding traces is a silly idea, maybe it should also say "you might get an exception"?

The error is benign: The removed trace is removed from the model, and then it's removed from the trace, but the trace didn't have it because it was already hidden..
Anyway, I'll fix it.

**Comment by willrogers** [comment]
Thanks.
