### ISSUE TITLE
BOY examples need version upped?

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1533]
The BOY examples give this error:

![image](https://cloud.githubusercontent.com/assets/854021/11902126/a86b2648-a57d-11e5-9d4c-38f1726a86c0.png)

Is this from the version up we did?  Do they need to be in sync?

**Comment by kasemir** [comment]
I have always seen that error because the example main.opi does an exact `if(opiVersion.compareTo(BOYVersion)<0)`, so each nightly build with its time stamp qualifier results in 'outdated' examples.

Something like `if(opiVersion.getMajor() < BOYVersion.getMajor())` would be more tolerant, but I'm also OK with simply removing that script from the main.opi, because the examples are in fact outdated, #767, and that's not just a matter of version numbers.

**Comment by berryma4** [comment]
The plugin version is 5.0.0-snapshot for o.c.opibuilder.examples.  Where does this 4.0.999 come from?

**Comment by berryma4** [comment]
Ah, I see, it's in the BOY example file itself.

**Comment by berryma4** [comment]
I added the ```if(opiVersion.getMajor() < BOYVersion.getMajor())```
