### ISSUE TITLE
Executed Command argument parsing

### ISSUE THREAD

**Issue by nickbattam** [ControlSystemStudio/cs-studio#1672]
Action Buttons that contain Execute Command action associated with them failing to execute if the command string includes single-quoted arguments (e.g. `xterm -e 'console $macro'`). 

The argument parser inside the action class uses `org.csstudio.java.string.splitIgnoreInQuotes` to split the command string into a form that can be handled by Java's `Runtime.getRuntime().exec(...)`.

`splitIgnoreInQuotes` only ignores 'split' characters contained in nested (correctly escaped) double-quoted strings.

The problems we are seeing are on commands coming from our 1000s of converted EDM converted panels, so it would be a non-trivial task to change them all.

I think a better solution would be to extended the function to ignore 'split' characters inside nested single- or double-quoted strings. There are a set of test-cases already defined so I shouldn't break any of the 'standard' use-cases - the only other uses of this function appear to be linked to macro handling.

Are you happy for me to make this change?

**Comment by kasemir** [comment]
Not sure about "the _only_ other uses". The call hierarchy of splitIgnoreInQuotes() fills my screen. But that should be even more reason to do it right.

So go ahead, add a test case for the things that fail in the EDM converted panels, and then update splitIgnoreInQuotes() to make all tests pass again.

While at it, I'm afraid there's probably much more to doing it right, for example if you want to support escape chars which themselves are escaped. When it comes to macros being serialized/deserialized, we're probably better off doing that as XML, instead of inventing our own way and then trying to parse that with things like splitIgnoreInQuotes(). But that's for new code. For existing code, I guess the best you can do is assert that the unit tests for  splitIgnoreInQuotes() pass.
