### ISSUE TITLE
'Edit Embedded OPI' context menu

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1908]
We added the option to edit an opi from run mode in BOY.  

A further user request is to be able to edit the OPI that's contained in a linking container.  This might be either in run mode or in edit mode.

**Comment by kasemir** [comment]
This has also been implemented for the display builder:

In the runtime, right click anywhere to "Open in editor".
If this is done within an embedded display widget, it opens an editor for the embedded display instead of the top-level display.
If the display, embedded or top-level, is a remote http://.. link, there's a prompt for a local file name into which the display will be downloaded, and then the local copy is opened in the editor.

In the editor, the embedded display just shows the body, one cannot "touch" the widgets inside the embedded display. But when selecting the embedded display widget, the context menu "Edit Embedded Display" opens another editor for the embedded file.

Close this ticket?

**Comment by willrogers** [comment]
Fine for me.
