### ISSUE TITLE
snl plugins are missing in applications/p2repo configuration

### ISSUE THREAD

**Issue by rosarp** [ControlSystemStudio/cs-studio#1942]
Hi All,

I was building ITER product and found that it was not able to find two plugins from applications/snl/snl-plugins.
When I tracked back, I found that snl repository is not added in these two files.

1. https://github.com/ControlSystemStudio/cs-studio/blob/master/applications/p2repo/compositeArtifacts.xml
2. https://github.com/ControlSystemStudio/cs-studio/blob/master/applications/p2repo/compositeContent.xml

Can anyone confirm if they can be added or missed on purpose?

Regards

**Comment by kasemir** [comment]
The snl module is already listed in the parent pom, so it's compiled, but then as you noticed not added to the composite repo.

It was simply omitted because many sites don't include it in their product.
I'm OK with adding it to the composite repo, please create a pull request to update the p2repo files that you mentioned.
