### ISSUE TITLE
Help with EGU

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/cs-studio#2168]
Hello,

I wrote a simple OPI (BOY) with a Test Update widget connected to the loc://PV1 PV, and unit shown, then a Text Input connected to the same PV plus another one connected to the loc://PV1.EGU PV.

When I type a value inide the first Text Input the Text Update gets updated. But when I type something in the loc://PV1.EGU Text Input, the unit of the Text Update is not updated. Why? What's wrong?

I have DBE_PROPERTY Supported checked in my application properties.

Thank you in advance for any help.
Claudio

**Comment by kasemir** [comment]
*.EGU is a field of certain records.
loc:// PVs are not based on records.
Just like LabVIEW-based CA servers are not based on records.

For those you can still use a channel request of DBR_CTRL_* to fetch units, limits, ... but that doesn't mean you can access fields via individual channels, since there are no records and thus no such fields.
