### ISSUE TITLE
LED font color change works only for the first time

### ISSUE THREAD

**Issue by ihtao127** [ControlSystemStudio/cs-studio#2639]
I realy like the feature that the LED font changes the color base on the backgroud color, if the color is dark, the font changes to a white color, it is good for the readibility.

But it only works once when the OPI is initialized by running it or reload it.

Please look at [the video](https://youtu.be/qpW8GVofQXk).

**Comment by kasemir** [comment]
Since this is for the display builder and phoebus, you could have posted this issue there, not in the Eclipse/BOY based repo. But anyway, the display builder examples for "LED" contain a more reproducible setup since it's using local PVs, so anybody can execute that display. When I try it, the color changes as expected:

![Screen Shot 2020-04-15 at 8 57 11 AM](https://user-images.githubusercontent.com/1932421/79339630-28844380-7ef7-11ea-82a0-086c8ffc5e43.png)
![Screen Shot 2020-04-15 at 8 57 05 AM](https://user-images.githubusercontent.com/1932421/79339633-29b57080-7ef7-11ea-9a3f-9752c1c429bf.png)

Same with the "Byte Monitor" example:

![Screen Shot 2020-04-15 at 9 00 30 AM](https://user-images.githubusercontent.com/1932421/79339917-9af52380-7ef7-11ea-8543-dcb0e2e8746b.png)


What do you get for those examples?

**Comment by ihtao127** [comment]
Thank you very much for your answer and please forgive me to post this issue in the wrong repo.

I've had a look at the examples, and now I found the probable reason, maybe it is because my Enum PV doesn't have the right definition on the fields, which means that the bi record just have a "ONAM" filed and there's no "ZNAM" field.

I will fix the field definition and test this again.

Thank you again.

**Comment by ihtao127** [comment]
I have created a new issue in the **_[Phoebus repo](https://github.com/ControlSystemStudio/phoebus/issues/1269)_**.
