### ISSUE TITLE
Alarm/OPI interaction. PVs to display & ack’ alarms (Lead: Nadine - Reviewers: Eric)

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#803]
I have an awful version I use for one opi screen:
https://stash.nscl.msu.edu/projects/CF/repos/org.csstudio.pvmanager.jms.beast.feature/browse

**Comment by kasemir** [comment]
Notes from discussion at today's hangout..

Simpler TO-DO Items:
1) Core plugin for alarm colors (foreground, background) and icons to represent the alarm severities. Then use that in alarm plugins, opibuilder, any other place that wants to render alarms.

2) Alarm Table columns: Configure via preferences similar to message log history.
Replace with JavaFX Table? Would allow easy runtime changes to columns, may overall be a better table. But note that this change is primarily about configuring the columns once, and operators shouldn't need to (be able to?) change them at runtime.

3) Default 'double-click' action for Alarm Table.
.. mostly to open one designated related display.


Alarm PVs: PV for alarm ack, table PV for current alarms, …
This once looked like a great building block.
If the Alarm Table etc. don't work for you, create your own *.opi that talks to the alarm server.
--> Impossible?
Based on Eric's trials, no good fit for 'PV'. How to support alarm-specific context menus?


Alarm filtering:
Provide a 'Contextual' Alarm Table that uses E4 'Context' Variable for current alarm hierarchy level.
Set by Alarm Tree, or set by BOY Script, or set by new ITER navigational widget that updates linking containers, ...
Alarm Table only shows alarms below that level. Its tab name reflects the currently active alarm hierarchy level. Has option to show 'all', ignoring the alarm level context variable.

Not 100% if E4 context variable is the best mechanism, but looks like it at this time.
The Lars Vogel article http://www.vogella.com/articles/Eclipse4Services/article.html lists E4 communication mechanisms.
In E3, there was mostly the ISelectionProvider, one global selection mechanism.
If you want to pass updates on various model items between E4 components, you can use context variables.
Publishing anything into a context variable is as easy as publishing a selection, but note that you can now name the item that you put into the context. This allows you to publish different types of information under different names, effectively having access to multiple selection services.
You can either use a string or a class reference: 

public void methodThatPublishesContextVariable(final MWindow window)
{
    final IEclipseContext context = window.getContext();
    context.declareModifiable("alarm_level");
    context.set("alarm_level", "/The/Current/Alarm/Level");
}

Receiving the item updates is easy in E4 when you have injection support:
// E4 will invoke this whenever the named context variable changes.
@Inject
public void handleChangedAlarmLevel(
    @Optional
    @Named("alarm_level")
    final String level)
{
    System.out.println("Should filter alarms to level " + level);
}

Not sure how this would work with the compatibility layer, might need to somehow get the MWindow, then window.getContext() .. as done in other code that was adapted to E4.

**Comment by utzeln** [comment]
Let's start with adding a column for the alarm priority icon - by default, this column will be hidden.

Proposal for the icons:
![image](https://cloud.githubusercontent.com/assets/4686181/6895709/468f09b2-d6e3-11e4-9896-5fadfc658d7d.png)

**Comment by utzeln** [comment]
ITER requires also that to the left of each alarm there shall be an acknowledgement tick box. By default this column will be hidden.

**Comment by utzeln** [comment]
Regarding the requirement to have the alarm table layout configurable.

Preferences should allow to specify if a column is shown or hidden, to order the columns up and down, and to change the column properties such as the name of the column and its width. 

To be confirmed if the weight of the column has also to be taken into account as it is in the message history. 

The preference GUI could be based on the problems view “Configure Columns…” interface:
![image](https://cloud.githubusercontent.com/assets/4686181/6896368/ec220490-d6ea-11e4-8f0a-b5e110007bd2.png)

**Comment by utzeln** [comment]
The alarm table layout for ITER shall include the alarm action and alarm ID. Using the first guidance title  for the alarm ID and its details to describe the action, could do it. But this means that 2 additional columns are required - hidden by default.

**Comment by kasemir** [comment]
Regarding your icon proposal, using the basic Eclipse 'error' and 'warning' icons for major & minor alarms sounds reasonable.

I really like the added checked box for the 'acknowledged' version, especially when you add checkboxes for yet another way to acknowledge alarms. At the same time, I would then assert that icons which indicate acknowledged alarms are not confused with actual check boxes.
So instead of acknowledged alarm icon == full size check box with small 'error' decoration, maybe do it the other way around: acknowledged alarm icon == full size 'error' icon with check box decoration. That way, it's obvious that the check box is a decoration, and not a clickable check box.

I don't understand the icons for alarms cleared but not acknowledged.
Is that an "I" with decoration?
Again I'd base those on the full size error resp. warning icons but with decorations that indicate that the PV is again OK. Simplest case, add "OK" as a decoration. Or a green check mark.
So overall, more like this, where the main icon (error, warning, ..) stays similar but the decorations reflect acknowledged or recovered state detail:

![screen shot 2015-03-30 at 8 59 47 am](https://cloud.githubusercontent.com/assets/1932421/6896612/281677e0-d6bb-11e4-8ed3-c9c28d899f69.png)


Finally, what about invalid and undefined alarms?
Could use something that indicates 'unplugged', like a version of the 'plug' icon that indicates that a PV is not fully 'plugged in', u.e. disconnected:
![screen shot 2015-03-30 at 9 05 43 am](https://cloud.githubusercontent.com/assets/1932421/6896703/3a0e8a2c-d6bc-11e4-8d50-d51fea0bf8ad.png)
![screen shot 2015-03-30 at 9 05 47 am](https://cloud.githubusercontent.com/assets/1932421/6896706/40a2d424-d6bc-11e4-8913-751f8d64a636.png)

**Comment by utzeln** [comment]
The "i" stands for Information - i.e. there was a problem, but now it's OK.

OK for having always the full size error and warning icons and adding decoration for checked/acknowledged and Information.

Good point regarding Invalid and undefined alarms. Icons are fine for me :).

**Comment by utzeln** [comment]
Updated icons:
![image](https://cloud.githubusercontent.com/assets/4686181/6982434/07978b62-da12-11e4-9267-64f7f9bbe442.png)

**Comment by utzeln** [comment]
To be discussed:
“Group By” option for acknowledged/un-acknowledged alarms: if false, all the alarms are displayed in the same table; if true (by default), alarms are displayed as of today in 2 parts - current alarms and acknowledged ones.

**Comment by kasemir** [comment]
The icons are good!
Note that EPICS used to have no alarm, minor, major, invalid, but V4 and the alarm system now support no alarm, minor, major, invalid, unknown. For icons, I think it's OK to treat invalid and unknown as the same.
You'll also need an icon for invalid(==unknown) + cleared-but-unacknowledged and  invalid(==unknown) + acknowledged. Could use the same (i) resp. checkmark overlay as minor and major icons.

Regarding "Group By":

Yes, this needs to be an option so that the original behavior where acknowledged alarms move to the bottom remains available.

When you select the new behavior that places all alarms, ack'ed or not, in one list, are they simply sorted by their org.csstudio.alarm.beast.SeverityLevel, as long as the user selects the severity column as the sorting criteria? Or do you want to sort them by selected column, plus another hidden sorting criteria based on ack'ed or unack'ed?

**Comment by jbobnar** [comment]
I assume the icons should be stored into a "common" plugin that also defines all the alarm colors etc. Are there any preferences on what that plugin should be called and where I should put it? How about "core/ui/ui-plugins/org.csstudio.ui.resources"?

**Comment by utzeln** [comment]
Summary of our last discussion regarding Icons:
![image](https://cloud.githubusercontent.com/assets/4686181/7019120/e4685aec-dd0c-11e4-9b0b-ff88fa20dd95.png)

When “Group By” acknowledged/un-acknowledged is set to false, then all alarms are shown in the same table. A “Sort By” option should also allow to specify which column is used to sort the alarms and if it is ascending order or not. And the setting can be changed at runtime by clicking on the header of the column.

For ITER, the sorting criteria will be based on the alarm level to list alarms in the following order:
1. Invalid / Unknown alarm
2. Major unacknowledged alarm
3. Minor unacknowledged alarm
4. Alarm cleared but unacknowledged - invalid, then major, then minor
5. Acknowledged alarm - invalid, then major, then minor.

Where there is more than one Invalid/Unknown, Major or Minor alarm (acknowledged or unacknowledged) these shall be ordered by time i.e. most recent at the top of the list. So this means that we have a main column "sorting by", and the second criteria - time - could be by default / hidden 
(i.e. not a user selection).

**Comment by jbobnar** [comment]
The images for "disconnected and cleared" and "disconnected and acknowledged" are too complex. The icons have to be 16px X 16px. The proposal above is ~22px and is already difficult to understand, what it shows. When shrunk to 16px it is just a mix of different colors. What, if we remove the stop sign on the top and put the checkbox and information circle there? 
![invalid_cleared_notack](https://cloud.githubusercontent.com/assets/5602519/7019624/452501d2-dd12-11e4-8693-f5f7205eb32c.png)
![invalid_ack](https://cloud.githubusercontent.com/assets/5602519/7019626/47dceb92-dd12-11e4-8230-00b6a743eeaf.png)

**Comment by utzeln** [comment]
Good for me, but in this case the position of (i) and checked box should also be changed for all levels of alarm cleared and acknowledged.

**Comment by berryma4** [comment]
I agree with the "core/ui/ui-plugins/org.csstudio.ui.resources", good idea.

**Comment by jbobnar** [comment]
Is everybody OK with Nadine's proposal to have the second sorting criterion locked to timestamp? Currently the second criterion is the PV name.

**Comment by kasemir** [comment]
What Nadine describes is the natural ordering based on the o.c.alarm.beast.SeverityLevel, using its ordinal.
That's what you get in the existing table view when the "severity" column is selected as the sort order.
.. but right now in separate tables for active and acknowledged alarms.

I'm OK with this, which I think is what you're proposing:
* Adding a new option GroupByAck = False which will remove the separate table for acknowledged alarms.
* Order and initial width of table columns can be configured. It applies to both the GroupByAck=True and False.
* For GroupByAck = False, all alarms appear in the first table, which becomes the only table. Otherwise, it behaves as before: When you select the Severity column, they'll be sorted by SeverityLevel.ordinal() as UNDEFINED, INVALID, MAJOR, MINOR, UNDEFINED_ACK, INVALID_ACK, MAJOR_ACK, MINOR_ACK (or also the other way around, MINOR_ACK first, UNDEFINED last, when the sort direction is toggled).
* Having "Sort by Severity", with direction such that UNDEFINED is on TOP, MINOR_ACK on bottom is the default (or a preference setting), but user can still click on other table headers to change the sorting criteria and/or direction.
* When several items have the same sorting criteria, you need a second sorting criteria. Right now, the o.c.alarm.beast.ui.alarmtable.AlarmComparator uses the alarm name because two items will never have the same name. You can make time that second sorting criteria, but two alarms could happen at the same time, so then you need to make name the 3rd criteria.

**Comment by berryma4** [comment]
ITER Requirements

- Severity Icons (based on combined latched and current severity)
- Additional alarm columns: alarm action and alarm ID
- Aknowledge by clicking an icon in the table
- New sorting order (only for the severity icons)
- Multiline text in the alarm cells
- Flashing icons 
- Double click on the alarm opens a display
- Combine/separate alarms into one/two tables
- Configure the order and list of columns in the alarm table
- Configure individual columns width, weight and title
- Filtering the content of the alarm table based on a (selected) node in the tree
- Multiple instances of the alarm table, each shoing alarms belonging to a particular node

**Comment by berryma4** [comment]
Status:
- Severity Icons (based on combined latched and current severity)
  - still needs tree icons (half icons)
- Additional alarm columns: alarm action and alarm ID
  - It's in, but still need may need discussion on implementation
- Acknowledge by clicking an icon in the table
  - Done
- New sorting order (only for the severity icons)
  - Current pull request solves, but need to agree on icon sort
- Multiline text in the alarm cells
  - Not implemented yet, up for discussion
  - Kunal mentioned lessons learned from logbook table, swt was bad
- Flashing icons
  - Not implemented yet, up for discussion
-

**Comment by berryma4** [comment]
Action items:
- Severity Icons (based on combined latched and current severity)
  - still needs tree icons (half icons) #1094
- New sorting order (only for the severity icons) #1093
  - Current pull request solves, but need to agree on icon sort

Then we meeting again on Wednesday 13th CS-Studio Status Hangout.

**Comment by berryma4** [comment]
This moves to 4.2

**Comment by berryma4** [comment]
@utzeln  can we close this with the wok in #1460
